name: feature
description: to organize & track work on a new feature
title: "[feature]: "
labels: ["documentation"]
projects: ["commuter-copilot/commuter-copilot"]
assignees:
  - a-beacon42
type: "feature"
body:
  - type: textarea
    id: details
    attributes:
      label: details
      placeholder: add details about the feature
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: acceptance criteria
      placeholder: what is delivered for this feature
    validations:
      required: true
