name: story
description: logical unit of work under a parent feature
title: "[story]: "
labels: ["documentation"]
projects: ["commuter-copilot/commuter-copilot"]
assignees:
  - a-beacon42
type: "story"
body:
  - type: textarea
    id: details
    attributes:
      label: details
      placeholder: add details about the story
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: acceptance criteria
      placeholder: what is delivered for this story
    validations:
      required: true
