name: task
description: single step for completing a story
title: "[task]: "
labels: [""]
projects: ["commuter-copilot/commuter-copilot"]
assignees:
  - a-beacon42
type: "task"
body:
  - type: textarea
    id: details
    attributes:
      label: details
      placeholder: add details about the task
    validations:
      required: false
